services:
  - type: web
    name: jschart-backend
    env: node
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install --production
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://jschart-night.vercel.app
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - server/**
        - package.json
        - package-lock.json 